#!/bin/sh

NAME=$1
if [ -z $NAME ]; then
  echo "ERROR: you must provide a name for the shortcut -> \$NAME.desktop"
  exit 1
fi

SHORTCUT=~/dotfiles/desktop/.local/share/applications/$NAME.desktop

echo "Creating shortcut at -> [$SHORTCUT]"
mv ~/Desktop/chrome*.desktop $SHORTCUT
#cd ~/dotfiles
#stow destkop
