#!/bin/bash

LOGICAL_VOLUME="$1"
SIZE_TO_ADD="$2"

usage() {
  cat <<-EOF

  USAGE

    $0 <logical_volume> <size_to_add>

  ARGUMENTS

    <logical_volume> - path to LV in /dev/mapper
    <size_to_add> - numerical size with unit (ie - 10G)
EOF
}

if [ ! -f "$LOGICAL_VOLUME" ]; then
  usage
  exit 1
fi

if [ -z "$SIZE_TO_ADD" ]; then
  usage
  exit 1
fi

sudo lvextend -L +"$SIZE_TO_ADD" "$LOGICAL_VOLUME"
sudo resize2fs "$LOGICAL_VOLUME"
