#!/bin/bash

gsettings get org.gnome.system.proxy mode | grep -q manual
if [ $? -eq 0 ]; then
  echo -e "GNOME Proxy [${MM_GREEN}ON${NC}]"
else
  echo -e "GNOME Proxy -> [${MM_RED}OFF${NC}]"
fi

. proxytoggle show_settings
