#!/bin/bash

usage() {
	cat <<EOF
SUMMARY

    $0 - read password from LastPass

DESCRIPTION

    This script reads passwords from LassPass using the LastPass CLI.  It takes
    the unique ID of a LastPass entry as its argument.

    The default behavior is to copy the password to the System clipboard (via xclip ??).
    If you pass the -p option, it will print the password to STDOUT.

    If you are not logged into a LastPass session, this script will prompt you for
    your LastPass master password via a pop-up window.

REQUIRES

    LASTPASS_USERNAME  must be set in environment (ie - from ~/.local/.bash_env)

OPTIONS

    -h  print this help page

    -p  print password to STDOUT rather than to System clipboard

EOF
}

if [ -z "$LASTPASS_USERNAME" ]; then
  echo "LASTPASS_USERNAME must be set in the environment"
  exit 1
fi

OUTPUT_TO_CLIP="--clip"
while getopts "hp:" opt
do
  case "$opt" in
	  h)
      usage
      exit 1
      ;;
    p)
      OUTPUT_TO_CLIP=""
      shift
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

LASTPASS_ID=$1

if [ -z "$LASTPASS_ID" ]; then
  echo "You must provide: <LASTPASS_id>"
  echo "Use -h for help info"
  exit 1
fi

if ! lpass ls 2&>/dev/null ; then
  lpass login "$LASTPASS_USERNAME"
fi

if [ -z "$OUTPUT_TO_CLIP" ]; then
  lpass show --password "$LASTPASS_ID"
else
  lpass show --password "$OUTPUT_TO_CLIP" "$LASTPASS_ID"
fi
