#!/bin/bash

HOST=$1
PORT=${2:-443}

test ! -z "$HOST" || { echo "You must provide '<host> [<port>]'"; exit -1; }

openssl s_client -connect "$HOST:$PORT" -showcerts </dev/null 2>/dev/null \
  | openssl x509 -noout -subject -dates
