#!/bin/bash

# From (w/ a bunch of mods):
#   -> https://unix.stackexchange.com/questions/613103/how-to-run-a-tmux-command-across-all-panes-in-a-single-or-multiple-sessions

if [[ -z $1 ]]; then
    current=$(tmux display -p "#S")
    echo "usage: tmux-sendall SESSION [COMMAND]"
    if [[ -n $current ]]; then
        echo "current session: $current"
    fi
    exit 1
else
    session="$1"
fi

if [[ -n $2 ]]; then
    cmd="$2"
else
  read -p "Enter command (in quotes) to session -> [$session]: " cmd
    if [[ -z $cmd ]]; then exit 1; fi
fi


tmux_send_window() {
    # $1=target
    # $2=command

    ARE_PANES_SYNCHRONIZED=$(tmux display -p -t $1 "#{?pane_synchronized,yes,no}")
    if [ "$ARE_PANES_SYNCHRONIZED" = "no" ]; then
      tmux setw -t $1 synchronize-panes on
    fi
    tmux send-keys -lt "$1" "$2"
    tmux send-keys -t "$1" "Enter"
    tmux setw -t $1 synchronize-panes off
}

# This export does not go outside this script FYI; it is needed for bash command below
export -f tmux_send_window

tmux list-windows -t $session \
  | cut -d: -f1 \
  | xargs -I{} bash -c "tmux_send_window '$session:{}' '$cmd'"
