#!/bin/bash

WIDTH=1200
HEIGHT=800
X_CENTER_CORRECTION=0
Y_CENTER_CORRECTION=0

COMPUTED_HALF_X=$(( $(xrandr | grep \* | awk '{print $1}' | sed 's/x.*$//') / 2 ))
COMPUTED_HALF_Y=$(( $(xrandr | grep \* | awk '{print $1}' | sed 's/^.*x//') / 2 ))
echo "X_CENTER_CORRECTION=${X_CENTER_CORRECTION}"
echo "Y_CENTER_CORRECTION=${Y_CENTER_CORRECTION}"
echo "COMPUTED_HALF_X=${COMPUTED_HALF_X}"
echo "COMPUTED_HALF_Y=${COMPUTED_HALF_Y}"
echo

if [ "$1" = '-a' ]; then
  WINDOW=":ACTIVE:"
elif [ "$1" = '-s' ]; then
  WINDOW=":SELECT:"
# Custom-window name
elif [ -z "$1" ]; then
  echo -e "[${RED}ERROR${NC}] you must provide -> $0 [-a|-s|<window_name>] [-l] [<x_pos>] [<y_pos>]"
  echo
  wmctrl -l
  exit 1
else
  if [[ "$1" =~ ^[0-9]+$ ]]; then
    echo -e "[${RED}ERROR${NC}] not accepting all numeric window names b/c will confuse with X/Y positions"
    echo 
    wmctrl -l
    exit 1
  fi
  WINDOW="$1"
fi

# Laptop-centered
if [ "$2" = "-l" ]; then
  X_CENTER_CORRECTION=-600
  Y_CENTER_CORRECTION=-400
  # force ignoring of any additional provided arguments to script
  shift $#
fi

COMPUTED_X=$(( $COMPUTED_HALF_X + $X_CENTER_CORRECTION ))
COMPUTED_Y=$(( $COMPUTED_HALF_Y + $Y_CENTER_CORRECTION ))

X=${2:-$COMPUTED_X}
Y=${3:-$COMPUTED_Y}

if [ "$WINDOW" = ":ACTIVE:" ]; then
  CMD="wmctrl -r $WINDOW -b remove,maximized_horz,maximized_vert"
  echo -e "Running: [$CMD]"
  $CMD
fi

if [ "$WINDOW" = ":SELECT:" ]; then
  echo "Select the window to move/resize"
fi

CMD="wmctrl -r $WINDOW -e 0,$X,$Y,$WIDTH,$HEIGHT"
echo -e "Running: [$CMD]"
$CMD
