# Inserts a blank line between shell prompts
add_newline = true


# The '\' at the end of the line allows us to write the options on different
# lines but keep newlines from appearing between the options.  If you leave out
# the '\' then a newline will appear in the prompt at that point.
format = """
[┌───────────────────>](bold green)
[│](bold green)User: $username
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$gcloud\
$golang\
$nodejs\
$custom\
$cmd_duration\
$line_break\
$python\
$jobs\
$battery\
$time\
$status\
$shell\
[└─>](bold green) ${env_var.MODE_INDICATOR} $character"""
# $character"""
# $env_var\

right_format = """${env_var.MODE_INDICATOR}"""


[env_var.MODE_INDICATOR]
value = 'MODE_INDICATOR'
format = '[$env_value]($style)'
default = ''
style = 'bold cyan'

[battery]
disabled = false

[[battery.display]]
threshold = 90

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[directory]
truncation_length = 4
truncate_to_repo = false

[gcloud]
format = 'on [\[$symbol$active\]]($style) '

[kubernetes]
disabled = false

[nodejs]
disabled = false
detect_extensions = ["*", "js", "mjs", "py", "cjs", "ts"]

[package]
disabled = false
